# Generated by Django 4.0.3 on 2022-03-21 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_id', models.BigIntegerField(verbose_name='Id Produccion')),
                ('piece', models.CharField(max_length=255, verbose_name='pieza')),
                ('number', models.FloatField(verbose_name='numero')),
                ('quantity', models.FloatField(verbose_name='cantidad')),
                ('status', models.BigIntegerField(default=1, verbose_name='Status')),
                ('current_operator', models.BigIntegerField(blank=True, null=True, verbose_name='Operador Actual')),
                ('time', models.FloatField(verbose_name='tiempo')),
                ('machine_id', models.BigIntegerField(verbose_name='Id de la maquinaria')),
            ],
            options={
                'verbose_name': 'Ordenes',
                'verbose_name_plural': 'Ordenes',
            },
        ),
        migrations.CreateModel(
            name='HistoricalOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('production_id', models.BigIntegerField(verbose_name='Id Produccion')),
                ('piece', models.CharField(max_length=255, verbose_name='pieza')),
                ('number', models.FloatField(verbose_name='numero')),
                ('quantity', models.FloatField(verbose_name='cantidad')),
                ('status', models.BigIntegerField(default=1, verbose_name='Status')),
                ('current_operator', models.BigIntegerField(blank=True, null=True, verbose_name='Operador Actual')),
                ('time', models.FloatField(verbose_name='tiempo')),
                ('machine_id', models.BigIntegerField(verbose_name='Id de la maquinaria')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Ordenes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
