# Generated by Django 4.0.3 on 2022-04-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_historicalorder_status_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='pause',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Motivo de pausada'),
        ),
        migrations.AddField(
            model_name='order',
            name='pause',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Motivo de pausada'),
        ),
    ]
