# Generated by Django 4.0.3 on 2022-04-13 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
        ('orders', '0005_historicalorder_pause_order_pause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='machine_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='machines.machine'),
        ),
        migrations.AlterField(
            model_name='order',
            name='machine_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.machine'),
        ),
    ]
