# Generated by Django 4.0.3 on 2022-04-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_historicalorder_tratamiento_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='total_time',
            field=models.FloatField(blank=True, null=True, verbose_name='tiempo_total'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_time',
            field=models.FloatField(blank=True, null=True, verbose_name='tiempo_total'),
        ),
    ]
