# Generated by Django 4.0.3 on 2022-04-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_historicalorder_total_time_order_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='gcode',
            field=models.TextField(null=True, verbose_name='Detalles'),
        ),
        migrations.AddField(
            model_name='order',
            name='gcode',
            field=models.TextField(null=True, verbose_name='Detalles'),
        ),
    ]
