# Generated by Django 4.0.2 on 2022-07-07 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciondetail',
            name='cantidad',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='cotizaciondetail',
            name='costo_unitario',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='costo unitario'),
        ),
        migrations.AlterField(
            model_name='cotizaciondetail',
            name='cotizacion_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.cotizacion'),
        ),
    ]
