# Generated by Django 4.0.2 on 2022-07-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_alter_cotizaciondetail_cantidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizaciondetail',
            old_name='cotizacion_id',
            new_name='cotizacion',
        ),
    ]
