# Generated by Django 4.0.2 on 2022-07-07 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_rename_cotizacion_id_cotizaciondetail_cotizacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizaciondetail',
            old_name='cotizacion',
            new_name='cotizacion_id_id',
        ),
    ]
