# Generated by Django 4.0.2 on 2022-07-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_rename_cotizacion_cotizaciondetail_cotizacion_id_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizaciondetail',
            old_name='cotizacion_id_id',
            new_name='cotizacion_id',
        ),
    ]
