# Generated by Django 4.0.2 on 2022-07-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0005_rename_cotizacion_id_id_cotizaciondetail_cotizacion_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizaciondetail',
            old_name='cotizacion_id',
            new_name='cotizacion',
        ),
    ]
