# Generated by Django 4.0.2 on 2022-07-08 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0006_rename_cotizacion_id_cotizaciondetail_cotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciondetail',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion', to='cotizaciones.cotizacion'),
        ),
    ]
