# Generated by Django 4.0.3 on 2022-03-16 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.BigIntegerField()),
                ('oc', models.BigIntegerField(blank=True, null=True)),
                ('cdolarpeso', models.FloatField(verbose_name='cotizacion peso dolar')),
                ('datein', models.DateField(verbose_name='fecha de ingreso')),
                ('dateout', models.DateField(verbose_name='fecha prevista')),
                ('detail', models.TextField(blank=True, max_length=255, null=True, verbose_name='Detalles')),
                ('piece', models.BigIntegerField(verbose_name='pieza')),
                ('quantity', models.FloatField(verbose_name='Cantidad')),
                ('material', models.BigIntegerField(verbose_name='material')),
                ('tratamiento', models.BigIntegerField(verbose_name='tratamiento')),
            ],
            options={
                'verbose_name': 'Produccion',
                'verbose_name_plural': 'Produccion',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProduction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('client', models.BigIntegerField()),
                ('oc', models.BigIntegerField(blank=True, null=True)),
                ('cdolarpeso', models.FloatField(verbose_name='cotizacion peso dolar')),
                ('datein', models.DateField(verbose_name='fecha de ingreso')),
                ('dateout', models.DateField(verbose_name='fecha prevista')),
                ('detail', models.TextField(blank=True, max_length=255, null=True, verbose_name='Detalles')),
                ('piece', models.BigIntegerField(verbose_name='pieza')),
                ('quantity', models.FloatField(verbose_name='Cantidad')),
                ('material', models.BigIntegerField(verbose_name='material')),
                ('tratamiento', models.BigIntegerField(verbose_name='tratamiento')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Produccion',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
