# Generated by Django 4.0.3 on 2022-03-18 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_remove_historicalprovider_type_client_and_more'),
        ('clients', '0001_initial'),
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduction',
            name='client_name',
            field=models.CharField(max_length=255, null=True, verbose_name='nombre del cliente'),
        ),
        migrations.AddField(
            model_name='historicalproduction',
            name='number',
            field=models.CharField(max_length=20, null=True, verbose_name='codigo'),
        ),
        migrations.AddField(
            model_name='historicalproduction',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='observaciones'),
        ),
        migrations.AddField(
            model_name='historicalproduction',
            name='provider',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='providers.provider'),
        ),
        migrations.AddField(
            model_name='historicalproduction',
            name='provider_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduction',
            name='status',
            field=models.IntegerField(default=0, verbose_name='estatus'),
        ),
        migrations.AddField(
            model_name='historicalproduction',
            name='time',
            field=models.BigIntegerField(default=0, verbose_name='tiempo'),
        ),
        migrations.AddField(
            model_name='production',
            name='client_name',
            field=models.CharField(max_length=255, null=True, verbose_name='nombre del cliente'),
        ),
        migrations.AddField(
            model_name='production',
            name='number',
            field=models.CharField(max_length=20, null=True, verbose_name='codigo'),
        ),
        migrations.AddField(
            model_name='production',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='observaciones'),
        ),
        migrations.AddField(
            model_name='production',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.provider'),
        ),
        migrations.AddField(
            model_name='production',
            name='provider_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='status',
            field=models.IntegerField(default=0, verbose_name='estatus'),
        ),
        migrations.AddField(
            model_name='production',
            name='time',
            field=models.BigIntegerField(default=0, verbose_name='tiempo'),
        ),
        migrations.AlterField(
            model_name='historicalproduction',
            name='client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='historicalproduction',
            name='dateout',
            field=models.DateField(blank=True, null=True, verbose_name='fecha prevista'),
        ),
        migrations.AlterField(
            model_name='historicalproduction',
            name='material',
            field=models.CharField(max_length=255, verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='historicalproduction',
            name='oc',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Orden de compra'),
        ),
        migrations.AlterField(
            model_name='historicalproduction',
            name='piece',
            field=models.CharField(max_length=255, verbose_name='pieza'),
        ),
        migrations.AlterField(
            model_name='historicalproduction',
            name='quantity',
            field=models.FloatField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='production',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='production',
            name='dateout',
            field=models.DateField(blank=True, null=True, verbose_name='fecha prevista'),
        ),
        migrations.AlterField(
            model_name='production',
            name='material',
            field=models.CharField(max_length=255, verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='production',
            name='oc',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Orden de compra'),
        ),
        migrations.AlterField(
            model_name='production',
            name='piece',
            field=models.CharField(max_length=255, verbose_name='pieza'),
        ),
        migrations.AlterField(
            model_name='production',
            name='quantity',
            field=models.FloatField(default=1, verbose_name='Cantidad'),
        ),
    ]
