# Generated by Django 4.0.3 on 2022-03-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0002_historicalproduction_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduction',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='historicalproduction',
            name='piece',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='pieza'),
        ),
        migrations.AlterField(
            model_name='historicalproduction',
            name='tratamiento',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='tratamiento'),
        ),
        migrations.AlterField(
            model_name='production',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='production',
            name='piece',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='pieza'),
        ),
        migrations.AlterField(
            model_name='production',
            name='tratamiento',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='tratamiento'),
        ),
    ]
