# Generated by Django 4.0.3 on 2022-03-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0003_alter_historicalproduction_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduction',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='historicalproduction',
            name='provider_name',
        ),
        migrations.RemoveField(
            model_name='production',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='production',
            name='provider_name',
        ),
        migrations.AddField(
            model_name='historicalproduction',
            name='currency',
            field=models.FloatField(default=0, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='production',
            name='currency',
            field=models.FloatField(default=0, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='historicalproduction',
            name='cdolarpeso',
            field=models.FloatField(blank=True, null=True, verbose_name='cotizacion peso dolar'),
        ),
        migrations.AlterField(
            model_name='production',
            name='cdolarpeso',
            field=models.FloatField(blank=True, null=True, verbose_name='cotizacion peso dolar'),
        ),
    ]
