# Generated by Django 4.0.3 on 2022-03-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0004_remove_historicalproduction_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduction',
            name='client',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='cliente_id'),
        ),
        migrations.AlterField(
            model_name='historicalproduction',
            name='provider',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='provider_id'),
        ),
        migrations.AlterField(
            model_name='production',
            name='client',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='cliente_id'),
        ),
        migrations.AlterField(
            model_name='production',
            name='provider',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='provider_id'),
        ),
    ]
