# Generated by Django 4.0.2 on 2022-05-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripcion')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='planos/', verbose_name='plano')),
            ],
            options={
                'verbose_name': 'Planos',
                'verbose_name_plural': 'Planos',
            },
        ),
    ]
