# Generated by Django 4.0.3 on 2022-04-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_mantenimiento_date_mantenimiento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
